hive: exit code on certain error conditions

diff --git a/roles/hive/templates/helpers.sh.j2 b/roles/hive/templates/helpers.sh.j2
--- a/roles/hive/templates/helpers.sh.j2
+++ b/roles/hive/templates/helpers.sh.j2
@@ -21,14 +21,15 @@ HIVE_CLIENT_CONFIG_FLAG="-client-file={{ hive_dir_scripts }}/client-config.yaml"
 
 # Logs a message with timestamp
 function log {
-  echo -e "\033[36m[$(date '+%Y-%m-%d %H:%M:%S')]\033[0m $1"
+  echo -e "\033[36m[$(date '+%Y-%m-%d %H:%M:%S')]\033[0m (HIVE-SERVICE) $1"
 }
 
 # Updates the hive test results index file
 function updateIndex {
   log "updating index at $HIVE_RESULTS_PATH"
   cd $HIVE_HOME_PATH
-  $HIVEVIEW_BIN_PATH -listing -logdir "$HIVE_RESULTS_PATH" > "${HIVE_WEB_PATH}/listing.jsonl.tmp"
+  $HIVEVIEW_BIN_PATH -listing -logdir "$HIVE_RESULTS_PATH" > "${HIVE_WEB_PATH}/listing.jsonl.tmp" \
+    || { log "failed to update web index"; exit 1; }
   cp "${HIVE_WEB_PATH}/listing.jsonl.tmp" "${HIVE_WEB_PATH}/listing.jsonl"
   log "updating index done"
 }
@@ -37,11 +38,14 @@ function updateIndex {
 function updateRepo {
   log "fetching repo code: "
   if [ ! -d "$HIVE_HOME_PATH/.git" ]; then
-    git clone --depth 1 --branch "$HIVE_VERSION" "$HIVE_REPO_ADDRESS" "$HIVE_HOME_PATH"
+    git clone --depth 1 --branch "$HIVE_VERSION" "$HIVE_REPO_ADDRESS" "$HIVE_HOME_PATH" \
+      || { log "failed to clone hive repo"; exit 1; }
   fi
   cd $HIVE_HOME_PATH
-  git pull "${HIVE_REMOTE}"
-  git checkout "${HIVE_REMOTE}/${HIVE_VERSION}"
+  git pull "${HIVE_REMOTE}" \
+    || { log "failed to pull hive repo"; exit 1; }
+  git checkout "${HIVE_REMOTE}/${HIVE_VERSION}" \
+    || { log "failed to checkout hive repo"; exit 1; }
   log "fetching repo code done"
   buildHive && deployHiveWeb
 }
@@ -53,14 +57,16 @@ function buildHive {
   log "building hive"
   ( cd $HIVE_HOME_PATH \
     && go build -o $HIVE_BIN_PATH . \
-    && go build -o $HIVEVIEW_BIN_PATH ./cmd/hiveview )
+    && go build -o $HIVEVIEW_BIN_PATH ./cmd/hiveview ) \
+    || { log "failed to build hive binaries"; exit 1; }
   log "building hive done"
 }
 
 # Deploys the files required for the hive web interface
 function deployHiveWeb {
   log "deploying hive web"
-  $HIVEVIEW_BIN_PATH -deploy $HIVE_WEB_PATH
+  $HIVEVIEW_BIN_PATH -deploy $HIVE_WEB_PATH \
+    || { log "failed to deploy hive web"; exit 1; }
   log "deploying hive web done"
 }
 
@@ -79,7 +85,8 @@ function pruneDocker {
 function pruneTestResults {
   local keep_logs_for=${1:-"720h"} # 30 days
   log "pruning old test results, greater than $keep_logs_for)"
-  $HIVEVIEW_BIN_PATH -gc -logdir $HIVE_RESULTS_PATH -keep $keep_logs_for
+  $HIVEVIEW_BIN_PATH -gc -logdir $HIVE_RESULTS_PATH -keep $keep_logs_for \
+    || { log "failed to prune old test results"; exit 1; }
   log "pruning old test results done"
 }
 
